### ISSUE TITLE
Twitter Bot Favoriting Tweets

### ISSUE THREAD

**Issue by frankpantone** [syn74x/Twitter_RT-FV_bot#1]
Hey man,

Not necessarily an issue and appreciate you sharing your twitter bot! I was wondering how one would modify your script to only favorite tweets instead of Favoriting and re tweeting them?

Following users would be fine but I would like to remove the option to re tweet the tweets.

Any insight would be greatly appreciated.

**Comment by syn74x** [comment]
Hey there.

Apologies for the slow response. I'm In Canada right now and am not paying full attention to my Laptop.

The function at the end of the script called run() creates a loop that first runs rt_fv() with re-tweet parameters and then runs it with favorite parameters.

If you comment out / remove line 46 this will only run the loop with favorites. If you didn't want to follow the users you can comment out / remove lines 37, 38 and 39.

If you have a hard time with this let me know and I can edit the script for you and ping you a copy. 

Regards

Syn

**Comment by frankpantone** [comment]
Hey,

Thanks a lot for the reply. Canada is a nice country, I used to go there all the time from the USA. I'll take a look at your advice, and see what I can come up with. The reason I ask, is I found that the BOT has been retweeting Ad's for my competitors at times which is obviously not good but So far the twitter bot has been working pretty well for me. 

Do you have any interest in creating any other bots for other social networks?

Best Regards,

Pudy

**Comment by syn74x** [comment]
I can totally see why re-tweeting material from your competitors is a problem.

One way round that happening would be to create a blacklist of users to never re-tweet, wouldn't take  great deal of work to implement. Although as the market changes and expands the list would need to be maintained to some degree, but not a huge issue to add extra user names into a list.

Either way if you need me to tweak the code to suit your needs just let me know what you want it to do and I can whip you up a customized version of it.

What other social media were you thinking of using bots for? I haven't spent a great deal of time looking into the API's, but thats only because I haven't needed to.

**Comment by syn74x** [comment]
I made a new repo and stripped out the re-tweet functionality for you.

https://github.com/syn74x/Twitter_FV_bot

It should work exactly the same as before and I gave it a quick run on my VPS to make sure nothing got broken in the process. 

If you want to change the wait time you can alter the min_time (line 10) and max_time (line 13) variables to whatever suits you best. Currently it will favorite, on average, every 15 mins. I wanted to give this a random element, to make it feel a bit more organic, rather than bang on every 15 mins and I set it to an average of 15 mins because I didn't want to spam my followers too much. I'm sure for favorites you could reduce this a lot without issue, although I'm not sure what would be considered too low and risk a ban. For testing purposes it might be worth making an alt account that you can try things out on without risking your main account.

I've used instabot.py myself and haven't had any connection problems with it, so it's not an issue with the script itself. There's a couple of options you could try. Running a Virtual Machine for your scripts, with the network set to bridged, is one option. Alternatively a Virtual Private Server is an option to keep stuff running 24/7. This comes with a monthly cost, although it's not a huge amount. A Raspberry Pi is also a very cheap option, not expensive to buy and the power requirements are low so leaving it going all the time is viable.

I've not come across any bots for FB, although I'm sure they're out there and it must have an API. As a platform I'm not a big fan of it as I find it pretty obtrusive, although I know that it has the ability to reach a massive audience. I'm pretty sure the way to get the traffic through FB is with paid options. I've had a page for stuff I've done relative to DJ'ing and it seems to work very differently to personal pages regrading post visibility. 

I'll have a look at that linkedIn bot in the morning!

**Comment by frankpantone** [comment]
Thanks man I really appreciate it!

Do you have any experience with web development?

**Comment by syn74x** [comment]
No Worries

Unfortunately I don't have much experience with web dev work. I generally do hardware and software support. Python and Cisco are what I'm currently working on to expand my knowledge base.
